services:
  nwn:
    platform: linux/amd64
    image: nwnxee/unified:latest
    container_name: nwn-ee-pw
    environment:
      - NWN_MODULE=NV_PW_Seed
      - NWN_SERVERNAME=NWN PW Seed (Local)
      - NWN_PUBLICSERVER=1
      - NWN_PORT=5121
      - NWN_MAXCLIENTS=16
      - NWN_SERVERVAULT=1
    ports:
      - "5121:5121/udp"
      - "5121:5121/tcp"
    volumes:
      - ../module:/nwn/run/modules
      - ../servervault:/nwn/home/servervault
      - ../database:/nwn/home/database
      - ../logs:/nwn/run/logs
    restart: unless-stopped
